import type { SupportedLocale } from '@/lib/i18n/locales';
import { adminLocaleKey } from '@/lib/localization/admin-copy';

const en = {
  Admin: 'Admin',
  'Admin navigation': 'Admin navigation',
  'Admin workspaces': 'Admin workspaces',
  Analytics: 'Analytics',
  'Analytics sections': 'Analytics sections',
  'Audit log': 'Audit log',
  'Audit trail': 'Audit trail',
  'Business metrics, orders, inventory, and site signals.': 'Business metrics, orders, inventory, and site signals.',
  Catalog: 'Catalog',
  Categories: 'Categories',
  category: 'category',
  categories: 'categories',
  'Configure auth': 'Configure auth',
  Content: 'Content',
  'Customer Ops': 'Customer Ops',
  Customers: 'Customers',
  Discounts: 'Discounts',
  Homepage: 'Homepage',
  Inquiries: 'Inquiries',
  'Jump to analytics section': 'Jump to analytics section',
  'Jump to overview section': 'Jump to overview section',
  'Launch checks': 'Launch checks',
  media: 'media',
  'Media library': 'Media library',
  'Operations console': 'Operations console',
  Orders: 'Orders',
  Overview: 'Overview',
  'Overview sections': 'Overview sections',
  Products: 'Products',
  product: 'product',
  products: 'products',
  Readiness: 'Readiness',
  Sales: 'Sales',
  Security: 'Security',
  'Security events': 'Security events',
  Settings: 'Settings',
  'Sign in': 'Sign in',
  'Signed in': 'Signed in',
  'Staff access': 'Staff access',
  'Staff readiness': 'Staff readiness',
  Store: 'Store',
  System: 'System',
  Translations: 'Translations',
  'Advanced cohorts': 'Advanced cohorts',
  'Business charts': 'Business charts',
  'Business summary': 'Business summary',
  'Cash collections': 'Cash collections',
  'Category sales': 'Category sales',
  'Dashboard groups': 'Dashboard groups',
  Fulfillment: 'Fulfillment',
  Guidance: 'Guidance',
  Inventory: 'Inventory',
  Payments: 'Payments',
  'Payment alerts': 'Payment alerts',
  'Payment methods': 'Payment methods',
  'Payment settlement': 'Payment settlement',
  'Product sales': 'Product sales',
  'Recent activity': 'Recent activity',
  Privacy: 'Privacy',
  'Retention status': 'Retention status',
  'Site funnel': 'Site funnel',
  'Order analytics': 'Order analytics',
  'Store configuration, staff access, and providers.': 'Store configuration, staff access, and providers.',
  'Products, categories, subcategories, and media.': 'Products, categories, subcategories, and media.',
  'Orders and customer inquiries.': 'Orders and customer inquiries.',
  'Profiles, addresses, accounts, and activity.': 'Profiles, addresses, accounts, and activity.',
  'Vouchers, campaigns, and gift-card planning.': 'Vouchers, campaigns, and gift-card planning.',
  'Readiness, access, audit, and security.': 'Readiness, access, audit, and security.',
  'Homepage copy and translations.': 'Homepage copy and translations.'
} as const;

const fa: Record<keyof typeof en, string> = {
  Admin: 'مدیر',
  'Admin navigation': 'ناوبری مدیریت',
  'Admin workspaces': 'بخش‌های مدیریت',
  Analytics: 'تحلیل‌ها',
  'Analytics sections': 'بخش‌های تحلیل',
  'Audit log': 'گزارش ممیزی',
  'Audit trail': 'ردیابی ممیزی',
  'Business metrics, orders, inventory, and site signals.': 'شاخص‌های کسب‌وکار، سفارش‌ها، موجودی و سیگنال‌های سایت.',
  Catalog: 'کاتالوگ',
  Categories: 'دسته‌بندی‌ها',
  category: 'دسته‌بندی',
  categories: 'دسته‌بندی',
  'Configure auth': 'تنظیم احراز هویت',
  Content: 'محتوا',
  'Customer Ops': 'عملیات مشتری',
  Customers: 'مشتریان',
  Discounts: 'تخفیف‌ها',
  Homepage: 'صفحه اصلی',
  Inquiries: 'درخواست‌ها',
  'Jump to analytics section': 'رفتن به بخش تحلیل',
  'Jump to overview section': 'رفتن به بخش نمای کلی',
  'Launch checks': 'بررسی‌های راه‌اندازی',
  media: 'رسانه',
  'Media library': 'کتابخانه رسانه',
  'Operations console': 'کنسول عملیات',
  Orders: 'سفارش‌ها',
  Overview: 'نمای کلی',
  'Overview sections': 'بخش‌های نمای کلی',
  Products: 'محصولات',
  product: 'محصول',
  products: 'محصول',
  Readiness: 'آمادگی',
  Sales: 'فروش',
  Security: 'امنیت',
  'Security events': 'رویدادهای امنیتی',
  Settings: 'تنظیمات',
  'Sign in': 'ورود',
  'Signed in': 'وارد شده',
  'Staff access': 'دسترسی تیم',
  'Staff readiness': 'آمادگی تیم',
  Store: 'فروشگاه',
  System: 'سیستم',
  Translations: 'ترجمه‌ها',
  'Advanced cohorts': 'گروه‌های پیشرفته',
  'Business charts': 'نمودارهای کسب‌وکار',
  'Business summary': 'خلاصه کسب‌وکار',
  'Cash collections': 'دریافت نقدی',
  'Category sales': 'فروش دسته‌بندی',
  'Dashboard groups': 'گروه‌های داشبورد',
  Fulfillment: 'ارسال',
  Guidance: 'راهنما',
  Inventory: 'موجودی',
  Payments: 'پرداخت‌ها',
  'Payment alerts': 'هشدارهای پرداخت',
  'Payment methods': 'روش‌های پرداخت',
  'Payment settlement': 'تسویه پرداخت',
  'Product sales': 'فروش محصول',
  'Recent activity': 'فعالیت اخیر',
  Privacy: 'حریم خصوصی',
  'Retention status': 'وضعیت نگهداری',
  'Site funnel': 'قیف سایت',
  'Order analytics': 'تحلیل سفارش‌ها',
  'Store configuration, staff access, and providers.': 'پیکربندی فروشگاه، دسترسی تیم و ارائه‌دهندگان.',
  'Products, categories, subcategories, and media.': 'محصولات، دسته‌بندی‌ها، زیرمجموعه‌ها و رسانه‌ها.',
  'Orders and customer inquiries.': 'سفارش‌ها و درخواست‌های مشتریان.',
  'Profiles, addresses, accounts, and activity.': 'پروفایل‌ها، نشانی‌ها، حساب‌ها و فعالیت‌ها.',
  'Vouchers, campaigns, and gift-card planning.': 'کوپن‌ها، کمپین‌ها و برنامه‌ریزی کارت هدیه.',
  'Readiness, access, audit, and security.': 'آمادگی، دسترسی، ممیزی و امنیت.',
  'Homepage copy and translations.': 'متن صفحه اصلی و ترجمه‌ها.'
};

export type AdminPageShellCopyKey = keyof typeof en;

export function getAdminPageShellCopy(key: string, locale?: SupportedLocale | string | null) {
  if (adminLocaleKey(locale) === 'fa' && key in fa) return fa[key as AdminPageShellCopyKey];
  if (key in en) return en[key as AdminPageShellCopyKey];
  return key;
}

export function createAdminPageShellTranslator(locale?: SupportedLocale | string | null) {
  return (key: string) => getAdminPageShellCopy(key, locale);
}
