import type { SupportedLocale } from '@/lib/i18n/locales';

export type AdminLocaleKey = 'en' | 'fa';

export type AdminCopyDictionary = Record<string, string>;

export function adminLocaleKey(locale?: SupportedLocale | string | null): AdminLocaleKey {
  return locale?.toLowerCase().startsWith('fa') ? 'fa' : 'en';
}

const fa: AdminCopyDictionary = {
  'Admin / Payments': 'مدیریت / پرداخت ها',
  'Admin authentication is not configured yet.': 'احراز هویت مدیریت هنوز تنظیم نشده است.',
  'Admin authentication is required to view settlement data.': 'برای مشاهده داده های تسویه، احراز هویت مدیریت لازم است.',
  'Admin authentication is required to view webhook alerts.': 'برای مشاهده هشدارهای وب هوک، احراز هویت مدیریت لازم است.',
  'Back to orders': 'بازگشت به سفارش ها',
  'Operation history': 'تاریخچه عملیات',
  'Payment operations': 'عملیات پرداخت',
  'Payment settlement': 'تسویه پرداخت',
  'Preview operations': 'پیش نمایش عملیات',
  'Provider readiness': 'آمادگی ارائه دهنده',
  'Refund and void operation pages are read-only Phase 33 diagnostics. They do not execute provider adapters, submit refunds or voids, mutate orders/payments, or release inventory/capacity.': 'صفحه های عملیات استرداد و ابطال فقط تشخیص خواندنی فاز ۳۳ هستند. آن ها adapter ارائه دهنده را اجرا نمی کنند، استرداد یا ابطال ثبت نمی کنند، سفارش/پرداخت را تغییر نمی دهند و موجودی یا ظرفیت را آزاد نمی کنند.',
  'Review payment webhook events that need operator attention, retries, or provider dashboard follow-up.': 'رویدادهای وب هوک پرداخت را که نیازمند توجه اپراتور، تلاش دوباره یا پیگیری در داشبورد ارائه دهنده هستند بررسی کنید.',
  'Review recent payment webhook events and compare provider-reported settlement data against checkout orders.': 'رویدادهای اخیر وب هوک پرداخت را بررسی کنید و داده های تسویه گزارش شده توسط ارائه دهنده را با سفارش های checkout مقایسه کنید.',
  'Settlement': 'تسویه',
  'Signed in as': 'وارد شده با حساب',
  'Webhook alerts': 'هشدارهای وب هوک',
  'Actions': 'عملیات',
  'Active': 'فعال',
  'Address': 'نشانی',
  'Active pipeline': 'جریان فعال',
  'Add follow-up': 'افزودن پیگیری',
  'Add image': 'افزودن تصویر',
  'Add image URL': 'افزودن نشانی تصویر',
  'Add media': 'افزودن رسانه',
  'All': 'همه',
  'All categories': 'همه دسته ها',
  'All owners': 'همه مسئول ها',
  'All products': 'همه محصولات',
  'Alt text': 'متن جایگزین',
  'Apply columns': 'اعمال ستون ها',
  'Assigned': 'تخصیص داده شده',
  'Assignment': 'تخصیص',
  'Assignment exports': 'خروجی های تخصیص',
  'Assignment filter': 'فیلتر تخصیص',
  'Available today': 'موجود امروز',
  'Back to categories': 'بازگشت به دسته ها',
  'Balance': 'مانده',
  'Belongs to': 'متعلق به',
  'Best': 'برتر',
  'Best seller': 'پرفروش',
  'Best sellers': 'پرفروش ها',
  'Blocked': 'مسدود',
  'Body': 'متن',
  'Bulk pick': 'انتخاب گروهی',
  'Campaign': 'کمپین',
  'Campaigns': 'کمپین ها',
  'Category': 'دسته',
  'Category saved successfully.': 'دسته با موفقیت ذخیره شد.',
  'Category image from media library': 'تصویر دسته از کتابخانه رسانه',
  'Category or subcategory': 'دسته یا زیردسته',
  'Category slots complete': 'جایگاه های کامل دسته',
  'Category translations': 'ترجمه های دسته',
  'Categories': 'دسته ها',
  'Categories and subcategories': 'دسته ها و زیردسته ها',
  'Channel': 'کانال',
  'Choose category': 'انتخاب دسته',
  'Checklist doc': 'سند چک لیست',
  'Clear': 'پاک کردن',
  'Closed': 'بسته شده',
  'CMS status': 'وضعیت CMS',
  'Code': 'کد',
  'Column visibility': 'نمایش ستون ها',
  'Complete': 'کامل',
  'Content workspace': 'فضای کاری محتوا',
  'Create and maintain the product catalog that powers the storefront. Assign products to any category or subcategory, manage homepage visibility, and update images from the media library.': 'کاتالوگ محصولاتی را که فروشگاه را تغذیه می کند بسازید و نگهداری کنید. محصولات را به هر دسته یا زیردسته متصل کنید، نمایش در صفحه اصلی را مدیریت کنید و تصاویر را از کتابخانه رسانه به روز کنید.',
  'Create category': 'ایجاد دسته',
  'Create category or subcategory': 'ایجاد دسته یا زیردسته',
  'Create product': 'ایجاد محصول',
  'Create products, assign them to categories or subcategories, control homepage flags, and update catalog imagery.': 'محصول بسازید، آن را به دسته یا زیردسته متصل کنید، پرچم های صفحه اصلی را کنترل کنید و تصاویر کاتالوگ را به روز کنید.',
  'Configure delivery, pickup, courier, and manual fulfillment options for checkout and staff workflows.': 'گزینه های ارسال، تحویل حضوری، پیک و انجام دستی را برای checkout و جریان کاری تیم تنظیم کنید.',
  'CSV': 'CSV',
  'CSV file': 'فایل CSV',
  'Customer requests': 'درخواست های مشتریان',
  'Database': 'پایگاه داده',
  'Database is not configured, so OTP security activity is unavailable in seeded preview mode.': 'پایگاه داده تنظیم نشده است، بنابراین فعالیت امنیتی OTP در حالت پیش نمایش داده نمونه در دسترس نیست.',
  'Database settings are unavailable until DATABASE_URL is configured.': 'تنظیمات پایگاه داده تا زمانی که DATABASE_URL تنظیم نشود در دسترس نیست.',
  'Default': 'پیش فرض',
  'Description': 'توضیحات',
  'Discounts are now represented in navigation so the admin shell has a stable place for voucher and campaign work.': 'تخفیف ها اکنون در ناوبری جایگاه ثابت دارند تا کارهای کوپن و کمپین در همین بخش ادامه پیدا کند.',
  'Draft': 'پیش نویس',
  'Edit': 'ویرایش',
  'Edit Persian and English homepage, product, and category translations, see publish state, and spot missing required copy. Existing base CMS fields remain the legacy fallback.': 'ترجمه های فارسی و انگلیسی صفحه اصلی، محصول و دسته را ویرایش کنید، وضعیت انتشار را ببینید و متن های ضروری ناقص را پیدا کنید. فیلدهای پایه CMS همچنان پشتیبان قدیمی هستند.',
  'Edit storefront copy and localized content without touching code.': 'متن فروشگاه و محتوای محلی سازی شده را بدون تغییر کد ویرایش کنید.',
  'Editing enabled': 'ویرایش فعال است',
  'Eligibility': 'شرایط اعمال',
  'Email': 'ایمیل',
  'Export CSV': 'خروجی CSV',
  'Events': 'رویدادها',
  'Export file as template': 'خروجی را به عنوان قالب استفاده کنید',
  'Eyebrow': 'برچسب بالا',
  'Filter': 'فیلتر',
  'Flags': 'پرچم ها',
  'Follow-up history': 'تاریخچه پیگیری',
  'Follow-up note': 'یادداشت پیگیری',
  'Follow-up note added successfully.': 'یادداشت پیگیری با موفقیت افزوده شد.',
  'Fulfillment methods': 'روش های انجام سفارش',
  'General / other': 'عمومی / سایر',
  'General inquiry': 'درخواست عمومی',
  'Generated': 'ایجاد شده در',
  'Hash': 'هش',
  'Hashes are truncated for display; hover to inspect the full hash.': 'هش ها برای نمایش کوتاه شده اند؛ برای دیدن هش کامل نشانگر را روی آن نگه دارید.',
  'Hero content': 'محتوای هیرو',
  'Homepage': 'صفحه اصلی',
  'Homepage content updated successfully.': 'محتوای صفحه اصلی با موفقیت به روز شد.',
  'Homepage and translations': 'صفحه اصلی و ترجمه ها',
  'Homepage best seller': 'پرفروش صفحه اصلی',
  'Homepage category': 'دسته صفحه اصلی',
  'Homepage hero': 'هیرو صفحه اصلی',
  'Homepage slots complete': 'جایگاه های کامل صفحه اصلی',
  'Homepage translations': 'ترجمه های صفحه اصلی',
  'Image': 'تصویر',
  'Image category': 'دسته تصویر',
  'Image file': 'فایل تصویر',
  'Image URL': 'نشانی تصویر',
  'Images': 'تصاویر',
  'Import CSV': 'درون ریزی CSV',
  'Import products': 'درون ریزی محصولات',
  'Inactive': 'غیرفعال',
  'Initial': 'اولیه',
  'item': 'مورد',
  'items': 'مورد',
  'Inquiry inbox': 'صندوق درخواست ها',
  'Inquiry updated successfully.': 'درخواست با موفقیت به روز شد.',
  'Inquiry notification retry runbook': 'راهنمای تلاش دوباره اعلان درخواست',
  'Jump to products': 'رفتن به محصولات',
  'Key': 'کلید',
  'Label': 'برچسب',
  'Launch checklist status': 'وضعیت چک لیست راه اندازی',
  'Linked item': 'مورد مرتبط',
  'Localization': 'محلی سازی',
  'Login required': 'ورود لازم است',
  'Manual category image URL': 'نشانی دستی تصویر دسته',
  'Manual product image URL': 'نشانی دستی تصویر محصول',
  'Media': 'رسانه',
  'Media columns': 'ستون های رسانه',
  'Media library': 'کتابخانه رسانه',
  'Media item saved successfully.': 'مورد رسانه با موفقیت ذخیره شد.',
  'Mine': 'مال من',
  'Missing': 'ناقص',
  'Missing image': 'تصویر ناقص',
  'Name': 'نام',
  'Needs copy': 'نیازمند متن',
  'Needs decision': 'نیازمند تصمیم',
  'Needs first review': 'نیازمند بررسی اولیه',
  'Next': 'بعدی',
  'No categories found': 'هیچ دسته ای پیدا نشد',
  'No follow-ups recorded yet.': 'هنوز پیگیری ثبت نشده است.',
  'No parent': 'بدون والد',
  'No recent hashed activity.': 'فعالیت هش شده جدیدی وجود ندارد.',
  'No product type': 'بدون نوع محصول',
  'No products found': 'هیچ محصولی پیدا نشد',
  'Overview workspace': 'فضای کاری نمای کلی',
  'Optional descriptive text': 'متن توصیفی اختیاری',
  'OTP auth activity': 'فعالیت احراز هویت OTP',
  'PII-safe summary of recent customer OTP request, delivery, and verification events. Raw phone numbers, IP addresses, user agents, and OTP codes are not shown.': 'خلاصه ای امن از نظر اطلاعات شخصی درباره درخواست، ارسال و تایید OTP مشتریان. شماره تلفن خام، نشانی IP، عامل کاربر و کدهای OTP نمایش داده نمی شوند.',
  'Operational checks based on': 'بررسی های عملیاتی بر اساس',
  'Panel body': 'متن پنل',
  'Panel eyebrow': 'برچسب بالای پنل',
  'Panel title': 'عنوان پنل',
  'Page': 'صفحه',
  'Parent category': 'دسته والد',
  'Phone': 'تلفن',
  'Pick': 'انتخاب',
  'Previous': 'قبلی',
  'Price': 'قیمت',
  'Primary CTA label': 'عنوان دکمه اصلی',
  'Primary CTA URL': 'نشانی دکمه اصلی',
  'Print': 'چاپ',
  'Print view': 'نمای چاپ',
  'Product': 'محصول',
  'Product saved successfully.': 'محصول با موفقیت ذخیره شد.',
  'Product columns': 'ستون های محصول',
  'Product flag': 'پرچم محصول',
  'Product image from media library': 'تصویر محصول از کتابخانه رسانه',
  'Product management': 'مدیریت محصول',
  'Product slots complete': 'جایگاه های کامل محصول',
  'Product translations': 'ترجمه های محصول',
  'Product type': 'نوع محصول',
  'Products': 'محصولات',
  'Production readiness': 'آمادگی تولید',
  'Promotion tables are not available in this database yet. Run Prisma setup and seed again to show demo discounts.': 'جدول های پروموشن هنوز در این پایگاه داده آماده نیستند. برای نمایش تخفیف های نمونه، تنظیمات Prisma و seed را دوباره اجرا کنید.',
  'Quote': 'استعلام',
  'Quote only': 'فقط استعلام',
  'Ready': 'آماده',
  'Ready to fulfill': 'آماده انجام',
  'Recommended next action': 'اقدام پیشنهادی بعدی',
  'Register external image URLs or upload local/dev images into': 'نشانی تصویر خارجی ثبت کنید یا تصاویر محلی/توسعه را در این مسیر بارگذاری کنید:',
  'Review incoming product requests, update their status, assign ownership, and keep a follow-up timeline.': 'درخواست های محصول را بررسی کنید، وضعیت را به روز کنید، مسئولیت را تخصیص دهید و خط زمانی پیگیری را نگه دارید.',
  'Runtime mode': 'حالت اجرا',
  'Sales workspace': 'فضای کاری فروش',
  'Save category': 'ذخیره دسته',
  'Save homepage': 'ذخیره صفحه اصلی',
  'Save inquiry': 'ذخیره درخواست',
  'Save method': 'ذخیره روش',
  'Search': 'جستجو',
  'Scheduling': 'زمان بندی',
  'Search name, phone, email, notes, product...': 'جستجوی نام، تلفن، ایمیل، یادداشت، محصول...',
  'Secondary CTA label': 'عنوان دکمه دوم',
  'Secondary CTA URL': 'نشانی دکمه دوم',
  'Security': 'امنیت',
  'Settings': 'تنظیمات',
  'Seed fallback policy': 'سیاست پشتیبان داده نمونه',
  'Seeded promotion campaigns': 'کمپین های نمونه پروموشن',
  'Seeded preview mode': 'حالت پیش نمایش داده نمونه',
  'Show on homepage': 'نمایش در صفحه اصلی',
  'Showing': 'نمایش',
  'Sign out': 'خروج',
  'Slug': 'اسلاگ',
  'Sort': 'ترتیب',
  'Sort order': 'ترتیب نمایش',
  'Source': 'منبع',
  'Staff notes': 'یادداشت تیم',
  'Status': 'وضعیت',
  'Store credits': 'اعتبارهای فروشگاه',
  'of': 'از',
  'Title': 'عنوان',
  'These cards are advisory and do not change CMS write permissions.': 'این کارت ها راهنما هستند و مجوزهای نوشتن CMS را تغییر نمی دهند.',
  'Title, code, slug...': 'عنوان، کد، اسلاگ...',
  'Today': 'امروز',
  'Top-level category': 'دسته سطح بالا',
  'Top IP hashes': 'هش های پرتکرار IP',
  'Top phone hashes': 'هش های پرتکرار تلفن',
  'Total inquiries': 'همه درخواست ها',
  'Translation editor': 'ویرایشگر ترجمه',
  'Translated body': 'متن ترجمه شده',
  'Translated description': 'توضیح ترجمه شده',
  'Translated eyebrow': 'برچسب ترجمه شده',
  'Translated image alt': 'متن جایگزین تصویر ترجمه شده',
  'Translated title': 'عنوان ترجمه شده',
  'Translations': 'ترجمه ها',
  'Unassigned': 'تخصیص نیافته',
  'Update category': 'به روز رسانی دسته',
  'Upload image': 'بارگذاری تصویر',
  'Usage': 'مصرف',
  'Use parent category to create subcategories. Products can be assigned to either top-level categories or nested subcategories.': 'برای ایجاد زیردسته از دسته والد استفاده کنید. محصولات می توانند به دسته های اصلی یا زیردسته ها وصل شوند.',
  'Value': 'مقدار',
  'View': 'مشاهده',
  'Vouchers': 'کوپن ها',
  'Waiting on customer': 'در انتظار مشتری',
  'Window': 'بازه',
  'Workflow': 'گردش کار'
  ,
  'Admin': 'مدیر',
  'Admin / Catalog': 'مدیریت / کاتالوگ',
  'Admin / Content': 'مدیریت / محتوا',
  'Admin login': 'ورود مدیریت',
  'Admin navigation': 'ناوبری مدیریت',
  'Admin password': 'رمز عبور مدیریت',
  'Admin auth is not configured. Set': 'احراز هویت مدیریت تنظیم نشده است. مقدار',
  'and': 'و',
  'in': 'در',
  'before using CMS writes.': 'را پیش از ویرایش CMS تنظیم کنید.',
  'Sign in to edit the CMS.': 'برای ویرایش CMS وارد شوید.',
  'Sign in to edit': 'برای ویرایش وارد شوید',
  'The admin dashboard is protected by an environment-based password gate. Full multi-user roles can be added later when customer accounts are introduced.': 'داشبورد مدیریت با رمز عبور مبتنی بر متغیرهای محیطی محافظت می‌شود. نقش‌های کامل چندکاربره بعدا هنگام افزودن حساب‌های مشتری قابل اضافه شدن هستند.',
  'Back to settlement': 'بازگشت به تسویه',
  'Blush rose bouquet': 'دسته گل رز صورتی',
  'Configure auth': 'تنظیم احراز هویت',
  'Control the live homepage hero, CTAs, trust chips, occasion section copy, footer text, every occasion tile, and featured pick shown on the homepage.': 'هیروی زنده صفحه اصلی، دکمه‌ها، نشان‌های اعتماد، متن بخش مناسبت‌ها، متن فوتر، همه کاشی‌های مناسبت و انتخاب‌های ویژه صفحه اصلی را کنترل کنید.',
  'Credentials': 'اطلاعات دسترسی',
  'disabled': 'غیرفعال',
  'Evidence needed': 'نیازمند شواهد',
  'Edit hero, calls to action, homepage sections, footer copy, displayed occasions, and featured picks.': 'هیرو، دکمه‌های اقدام، بخش‌های صفحه اصلی، متن فوتر، مناسبت‌های نمایش‌داده‌شده و انتخاب‌های ویژه را ویرایش کنید.',
  'Featured pick added.': 'انتخاب ویژه افزوده شد.',
  'Featured pick removed.': 'انتخاب ویژه حذف شد.',
  'Featured pick saved.': 'انتخاب ویژه ذخیره شد.',
  'Execution': 'اجرا',
  'Execution remains disabled. This page is navigation-only and does not call provider adapters, use Prisma, create operation records, mutate orders/payments, or release inventory/capacity.': 'اجرا همچنان غیرفعال است. این صفحه فقط برای ناوبری است و adapterهای ارائه‌دهنده را فراخوانی نمی‌کند، از Prisma استفاده نمی‌کند، رکورد عملیاتی نمی‌سازد، سفارش/پرداخت را تغییر نمی‌دهد و موجودی یا ظرفیت را آزاد نمی‌کند.',
  'Execution remains disabled. These diagnostics are informational only and do not submit refunds, void authorizations, provider requests, inventory/capacity release, or order/payment mutations.': 'اجرا همچنان غیرفعال است. این عیب‌یابی‌ها فقط اطلاع‌رسانی هستند و استرداد، ابطال مجوز، درخواست ارائه‌دهنده، آزادسازی موجودی/ظرفیت یا تغییر سفارش/پرداخت انجام نمی‌دهند.',
  'Flag': 'پرچم',
  'History request validation failed': 'اعتبارسنجی درخواست تاریخچه ناموفق بود',
  'Homepage editor': 'ویرایشگر صفحه اصلی',
  'Homepage occasion tile added.': 'کاشی مناسبت صفحه اصلی افزوده شد.',
  'Homepage occasion tile removed.': 'کاشی مناسبت صفحه اصلی حذف شد.',
  'Homepage occasion tile saved.': 'کاشی مناسبت صفحه اصلی ذخیره شد.',
  'Homepage saved.': 'صفحه اصلی ذخیره شد.',
  'Issues': 'مسائل',
  'Last updated': 'آخرین به‌روزرسانی',
  'Manage image uploads, URL media, category tags, and usage.': 'بارگذاری تصویر، رسانه‌های URL، برچسب‌های دسته و استفاده را مدیریت کنید.',
  'Migration': 'مهاجرت',
  'Migration confirmation required': 'تایید مهاجرت لازم است',
  'need review': 'نیازمند بررسی',
  'none': 'هیچ‌کدام',
  'No payment operation records have been persisted for this order. This read-only panel only displays rows after the target environment confirms the migration gate.': 'برای این سفارش هیچ رکورد عملیات پرداختی ذخیره نشده است. این پنل فقط پس از تایید دروازه مهاجرت در محیط هدف، ردیف‌ها را نمایش می‌دهد.',
  'Operation preview': 'پیش‌نمایش عملیات',
  'Operations console': 'کنسول عملیات',
  'Payment operation history': 'تاریخچه عملیات پرداخت',
  'Payment operation preview': 'پیش‌نمایش عملیات پرداخت',
  'Payment operation records unavailable': 'رکوردهای عملیات پرداخت در دسترس نیستند',
  'Payment provider readiness': 'آمادگی ارائه‌دهنده پرداخت',
  'Payments': 'پرداخت‌ها',
  'Preview sample validation failed': 'اعتبارسنجی نمونه پیش‌نمایش ناموفق بود',
  'Providers': 'ارائه‌دهندگان',
  'Read-only': 'فقط خواندنی',
  'Read-only action': 'اقدام فقط خواندنی',
  'Preview summary': 'خلاصه پیش‌نمایش',
  'Preview warnings': 'هشدارهای پیش‌نمایش',
  'Advisory transition plan': 'برنامه انتقال پیشنهادی',
  'Read-only Phase 33 landing page for refund and void operation diagnostics. These links surface planning, history, and provider-readiness views without submitting refunds, void authorizations, provider requests, or order/payment mutations.': 'صفحه ورودی فقط‌خواندنی فاز ۳۳ برای عیب‌یابی عملیات استرداد و ابطال. این پیوندها نماهای برنامه‌ریزی، تاریخچه و آمادگی ارائه‌دهنده را بدون ثبت استرداد، ابطال مجوز، درخواست ارائه‌دهنده یا تغییر سفارش/پرداخت نمایش می‌دهند.',
  'Read-only Phase 33 operation history entry point for persisted refund and void records. Provide an orderId query parameter to review migration-gated operation records without creating records, calling providers, or mutating orders/payments.': 'نقطه ورود فقط‌خواندنی فاز ۳۳ برای تاریخچه رکوردهای ذخیره‌شده استرداد و ابطال. برای بررسی رکوردهای پشت دروازه مهاجرت، پارامتر orderId را بدهید؛ بدون ساخت رکورد، فراخوانی ارائه‌دهنده یا تغییر سفارش/پرداخت.',
  'Read-only Phase 33 diagnostics for refund and void provider readiness. This page reports credential environment variable names, endpoint-mapping evidence, and provider-validation evidence without executing adapters, calling providers, creating records, or mutating orders/payments.': 'عیب‌یابی فقط‌خواندنی فاز ۳۳ برای آمادگی ارائه‌دهنده استرداد و ابطال. این صفحه نام متغیرهای محیطی دسترسی، شواهد نگاشت endpoint و شواهد اعتبارسنجی ارائه‌دهنده را بدون اجرای adapterها، فراخوانی ارائه‌دهندگان، ساخت رکورد یا تغییر سفارش/پرداخت گزارش می‌کند.',
  'Read-only Phase 33 preview entry point for refund and void planning. This page uses static sample data and does not submit refunds, void authorizations, create records, or call providers.': 'نقطه ورود پیش‌نمایش فقط‌خواندنی فاز ۳۳ برای برنامه‌ریزی استرداد و ابطال. این صفحه از داده نمونه ثابت استفاده می‌کند و استرداد، ابطال مجوز، ساخت رکورد یا فراخوانی ارائه‌دهنده انجام نمی‌دهد.',
  'Read-only diagnostics for provider-operation readiness. This panel exposes credential names, endpoint evidence state, and validation evidence state without secrets, provider calls, or execution controls.': 'عیب‌یابی فقط‌خواندنی برای آمادگی عملیات ارائه‌دهنده. این پنل نام‌های دسترسی، وضعیت شواهد endpoint و وضعیت شواهد اعتبارسنجی را بدون اسرار، فراخوانی ارائه‌دهنده یا کنترل اجرای عملیات نمایش می‌دهد.',
  'Read-only refund and void preview for operator review before any persistence, provider execution, order mutation, or payment attempt mutation is added.': 'پیش‌نمایش فقط‌خواندنی استرداد و ابطال برای بررسی اپراتور پیش از افزودن ذخیره‌سازی، اجرای ارائه‌دهنده، تغییر سفارش یا تغییر تلاش پرداخت.',
  'Refund / void provider readiness': 'آمادگی ارائه‌دهنده برای استرداد / ابطال',
  'Requested by': 'درخواست‌شده توسط',
  'Save': 'ذخیره',
  'Seed or static asset': 'داده نمونه یا دارایی ثابت',
  'Static': 'ثابت',
  'Supported operations': 'عملیات پشتیبانی‌شده',
  'This panel does not render a refund or void execution button.': 'این پنل دکمه اجرای استرداد یا ابطال نمایش نمی‌دهد.',
  'This panel does not render refund or void execution controls.': 'این پنل کنترل‌های اجرای استرداد یا ابطال را نمایش نمی‌دهد.',
  'These recommendations are read-only and apply only after future provider success, persistence, audit, and operator approval rules exist.': 'این پیشنهادها فقط خواندنی هستند و فقط پس از وجود قوانین موفقیت ارائه‌دهنده، ذخیره‌سازی، ممیزی و تایید اپراتور در آینده اعمال می‌شوند.',
  'Update': 'به‌روزرسانی',
  'media': 'رسانه',
  'ready': 'آماده',
  'refund': 'استرداد',
  'void': 'ابطال'
  ,
  'View storefront': 'مشاهده فروشگاه'
};

export function getAdminCopy(key: string, locale?: SupportedLocale | string | null) {
  if (adminLocaleKey(locale) === 'fa') return fa[key] ?? key;
  return key;
}

export function createAdminTranslator(locale?: SupportedLocale | string | null) {
  return (key: string) => getAdminCopy(key, locale);
}
