/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in many projects; keeping it committed makes
// typecheck reliable in fresh CI environments.
