import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createAdminPageShellTranslator, getAdminPageShellCopy } from '../../lib/localization/admin-page-shell-copy';

export async function runAdminPageShellCopyTests() {
  const fa = createAdminPageShellTranslator('fa-IR');
  assert.equal(fa('Operations console'), 'کنسول عملیات');
  assert.equal(fa('Admin navigation'), 'ناوبری مدیریت');
  assert.equal(fa('Admin workspaces'), 'بخش‌های مدیریت');
  assert.equal(fa('Overview sections'), 'بخش‌های نمای کلی');
  assert.equal(fa('Jump to overview section'), 'رفتن به بخش نمای کلی');
  assert.equal(fa('Security'), 'امنیت');
  assert.equal(fa('Analytics'), 'تحلیل‌ها');
  assert.equal(fa('Order analytics'), 'تحلیل سفارش‌ها');
  assert.equal(fa('Business metrics, orders, inventory, and site signals.'), 'شاخص‌های کسب‌وکار، سفارش‌ها، موجودی و سیگنال‌های سایت.');
  assert.equal(fa('Store'), 'فروشگاه');
  assert.equal(fa('Customer Ops'), 'عملیات مشتری');
  assert.equal(fa('System'), 'سیستم');
  assert.equal(fa('Products, categories, subcategories, and media.'), 'محصولات، دسته‌بندی‌ها، زیرمجموعه‌ها و رسانه‌ها.');
  assert.equal(fa('Payment settlement'), 'تسویه پرداخت');
  assert.equal(fa('Staff access'), 'دسترسی تیم');
  assert.equal(fa('product'), 'محصول');
  assert.equal(fa('products'), 'محصول');
  assert.equal(fa('category'), 'دسته‌بندی');
  assert.equal(fa('categories'), 'دسته‌بندی');
  assert.equal(fa('media'), 'رسانه');
  assert.equal(fa('Unmapped shell key'), 'Unmapped shell key');
  assert.equal(getAdminPageShellCopy('Sign in', 'en-CA'), 'Sign in');

  const helperSource = readFileSync('lib/localization/admin-page-shell-copy.ts', 'utf8');
  assert.match(helperSource, /createAdminPageShellTranslator/);
  assert.match(helperSource, /Operations console/);
  assert.match(helperSource, /Payment settlement/);
  assert.match(helperSource, /Overview sections/);
  assert.match(helperSource, /Jump to overview section/);
  assert.match(helperSource, /Order analytics/);
  assert.match(helperSource, /Business metrics, orders, inventory, and site signals\./);
  assert.match(helperSource, /Store configuration, staff access, and providers\./);

  const shellSource = readFileSync('components/admin/AdminPageShell.tsx', 'utf8');
  assert.match(shellSource, /createAdminPageShellTranslator\(locale\)/);
  assert.match(shellSource, /t\('Operations console'\)/);
  assert.match(shellSource, /t\('Admin navigation'\)/);
  assert.match(shellSource, /t\('Admin workspaces'\)/);
  assert.match(shellSource, /t\('Overview sections'\)/);
  assert.match(shellSource, /AdminOverviewJumpNav/);
  assert.match(shellSource, /props\.activeNavKey === 'overview'/);
  assert.match(shellSource, /href: '\/admin\/analytics'/);
  assert.match(shellSource, /key: 'analytics'/);
  assert.match(shellSource, /tab === 'analytics'/);
  assert.match(shellSource, /href: '#readiness'/);
  assert.match(shellSource, /href: '#security'/);
  assert.match(shellSource, /href: '#order-analytics'/);
  assert.match(shellSource, /href: '#staff-readiness'/);
  assert.match(shellSource, /href: '#audit-log'/);
  assert.match(shellSource, /t\(section\.label\)/);
  assert.match(shellSource, /t\(navLabels\[item\.key\]\)/);
  assert.match(shellSource, /t\(current\.label\)/);
  assert.match(shellSource, /t\(current\.description\)/);
  assert.match(shellSource, /productCount === 1 \? 'product' : 'products'/);
  assert.match(shellSource, /categoryCount === 1 \? 'category' : 'categories'/);
  assert.match(shellSource, /t\('media'\)/);
  assert.doesNotMatch(shellSource, /const copy = \{/);

  const analyticsRangeSource = readFileSync('lib/analytics/admin-analytics-range.ts', 'utf8');
  assert.match(analyticsRangeSource, /ADMIN_ANALYTICS_RANGE_DAYS = \[7, 30, 90\]/);
  assert.match(analyticsRangeSource, /DEFAULT_ADMIN_ANALYTICS_RANGE_DAYS = 30/);
  assert.match(analyticsRangeSource, /normalizeAdminAnalyticsRangeDays/);
  assert.match(analyticsRangeSource, /getAdminAnalyticsRangeStart/);
  assert.match(analyticsRangeSource, /isWithinAdminAnalyticsRange/);

  const analyticsRouteSource = readFileSync('app/admin/analytics/page.tsx', 'utf8');
  assert.match(analyticsRouteSource, /activeTab="analytics"/);
  assert.match(analyticsRouteSource, /activeNavKey="analytics"/);
  assert.match(analyticsRouteSource, /returnTo=\{returnTo\}/);
  assert.match(analyticsRouteSource, /type SearchParams = Record/);
  assert.match(analyticsRouteSource, /normalizeAdminAnalyticsRangeDays\(firstParam\(params\.range\)\)/);
  assert.match(analyticsRouteSource, /ADMIN_ANALYTICS_RANGE_DAYS\.map/);
  assert.match(analyticsRouteSource, /href=\{rangeHref\(days\)\}/);
  assert.match(analyticsRouteSource, /aria-current=\{active \? 'page' : undefined\}/);
  assert.match(analyticsRouteSource, /orderRevenueSummaryService\.summary\(\{ rangeDays \}\)/);
  assert.match(analyticsRouteSource, /siteAnalyticsSummaryService\.summary\(\{ rangeDays \}\)/);
  assert.match(analyticsRouteSource, /AdminOrderRevenueSummaryPanel/);
  assert.match(analyticsRouteSource, /AdminSiteAnalyticsPanel/);
  assert.match(analyticsRouteSource, /lightweight server-rendered business and site charts/);
  assert.match(analyticsRouteSource, /privacy-safe first-party events/);
  assert.match(analyticsRouteSource, /id="analytics-csv-exports"/);
  assert.match(analyticsRouteSource, /exportHref\('business', rangeDays\)/);
  assert.match(analyticsRouteSource, /exportHref\('site', rangeDays\)/);
  assert.match(analyticsRouteSource, /Download business CSV/);
  assert.match(analyticsRouteSource, /Download site CSV/);
  assert.match(analyticsRouteSource, /raw visitor sessions are not exported/);
  assert.match(analyticsRouteSource, /id="analytics-privacy-retention"/);
  assert.match(analyticsRouteSource, /Privacy and retention/);
  assert.match(analyticsRouteSource, /NEXT_PUBLIC_SITE_ANALYTICS_ENABLED=false/);
  assert.match(analyticsRouteSource, /raw site events up to 180 days/);
  assert.match(analyticsRouteSource, /site-analytics-privacy-retention-policy\.md/);
  assert.match(analyticsRouteSource, /sectionHref\('analytics-privacy-retention', rangeDays\)/);
  assert.match(analyticsRouteSource, /id="analytics-section-index"/);
  assert.match(analyticsRouteSource, /sectionHref\('order-analytics', rangeDays\)/);
  assert.match(analyticsRouteSource, /sectionHref\('business-analytics-charts', rangeDays\)/);
  assert.match(analyticsRouteSource, /sectionHref\('site-analytics', rangeDays\)/);
  assert.match(analyticsRouteSource, /sectionHref\('product-analytics', rangeDays\)/);
  assert.match(analyticsRouteSource, /sectionHref\('inventory-analytics', rangeDays\)/);
  assert.match(analyticsRouteSource, /sectionHref\('fulfillment-analytics', rangeDays\)/);
  assert.match(analyticsRouteSource, /sectionHref\('payment-analytics', rangeDays\)/);
  assert.match(analyticsRouteSource, /sectionHref\('inquiry-operations', rangeDays\)/);
  assert.match(analyticsRouteSource, /sectionHref\('readiness-analytics', rangeDays\)/);
  assert.match(analyticsRouteSource, /aria-label=\{labels\.sectionLabel\}/);
  assert.match(analyticsRouteSource, /Jump directly to the analytics area you need/);

  const policySource = readFileSync('docs/site-analytics-privacy-retention-policy.md', 'utf8');
  assert.match(policySource, /not a third-party tracking system/);
  assert.match(policySource, /Do Not Track/);
  assert.match(policySource, /raw event retention/);
  assert.match(policySource, /NEXT_PUBLIC_SITE_ANALYTICS_ENABLED=false/);

  const publicPolicySource = readFileSync('public/docs/site-analytics-privacy-retention-policy.md', 'utf8');
  assert.match(publicPolicySource, /Aggregate CSV exports/);
  assert.match(publicPolicySource, /raw visitor sessions/);

  const analyticsExportRouteSource = readFileSync('app/admin/analytics/export/route.ts', 'utf8');
  assert.match(analyticsExportRouteSource, /assertAdminRole\('owner'\)/);
  assert.match(analyticsExportRouteSource, /normalizeAdminAnalyticsRangeDays\(url\.searchParams\.get\('range'\)\)/);
  assert.match(analyticsExportRouteSource, /normalizeReport\(url\.searchParams\.get\('report'\)\)/);
  assert.match(analyticsExportRouteSource, /orderRevenueSummaryService\.summary\(\{ rangeDays \}\)/);
  assert.match(analyticsExportRouteSource, /productSalesAnalyticsService\.summary\(\{ rangeDays \}\)/);
  assert.match(analyticsExportRouteSource, /categorySalesAnalyticsService\.summary\(\{ rangeDays \}\)/);
  assert.match(analyticsExportRouteSource, /siteAnalyticsSummaryService\.summary\(\{ rangeDays \}\)/);
  assert.match(analyticsExportRouteSource, /text\/csv; charset=utf-8/);
  assert.match(analyticsExportRouteSource, /golara-analytics-\$\{report\}-\$\{rangeDays\}d\.csv/);
  assert.match(analyticsExportRouteSource, /raw session export/);
  assert.match(analyticsExportRouteSource, /Revenue excludes cancelled\/refunded\/voided orders/);
  assert.match(analyticsExportRouteSource, /'product_sales'/);
  assert.match(analyticsExportRouteSource, /'category_sales'/);
  assert.match(analyticsExportRouteSource, /average_unit_revenue_cents/);

  const chartPrimitiveSource = readFileSync('components/admin/AdminAnalyticsChartPrimitives.tsx', 'utf8');
  assert.match(chartPrimitiveSource, /AdminAnalyticsBarChart/);
  assert.match(chartPrimitiveSource, /AdminAnalyticsTrendChart/);
  assert.match(chartPrimitiveSource, /AdminAnalyticsChartDatum/);
  assert.match(chartPrimitiveSource, /role="list"/);
  assert.match(chartPrimitiveSource, /role="img"/);
  assert.match(chartPrimitiveSource, /<details/);
  assert.match(chartPrimitiveSource, /<table/);
  assert.match(chartPrimitiveSource, /<svg/);
  assert.match(chartPrimitiveSource, /<polyline/);
  assert.match(chartPrimitiveSource, /viewBox="0 0 100 100"/);
  assert.match(chartPrimitiveSource, /aria-label=\{title\}/);
  assert.match(chartPrimitiveSource, /style=\{\{ width: `\$\{percent\}%` \}\}/);

  const revenueSource = readFileSync('components/admin/AdminOrderRevenueSummaryPanel.tsx', 'utf8');
  assert.match(revenueSource, /id="order-analytics"/);
  assert.match(revenueSource, /scroll-mt-24/);
  assert.match(revenueSource, /AdminAnalyticsBarChart/);
  assert.match(revenueSource, /AdminAnalyticsTrendChart/);
  assert.match(revenueSource, /id="business-analytics-charts"/);
  assert.match(revenueSource, /formatRangeLabel\(summary\.analyticsRangeDays/);
  assert.match(revenueSource, /summary\.recentDaily\.map/);
  assert.match(revenueSource, /summary\.byStatus/);
  assert.match(revenueSource, /summary\.byCurrency\.map/);
  assert.match(revenueSource, /Orders over time/);
  assert.match(revenueSource, /Revenue over time/);
  assert.match(revenueSource, /Average order value over time/);
  assert.match(revenueSource, /Orders by status/);
  assert.match(revenueSource, /Revenue by currency/);
  assert.match(revenueSource, /id="inquiry-operations"/);
  assert.match(revenueSource, /id="product-analytics"/);
  assert.match(revenueSource, /id="inventory-analytics"/);
  assert.match(revenueSource, /id="fulfillment-analytics"/);
  assert.match(revenueSource, /id="activity-analytics"/);
  assert.match(revenueSource, /id="payment-analytics"/);
  assert.match(revenueSource, /id="readiness-analytics"/);

  const globalStyles = readFileSync('app/globals.css', 'utf8');
  assert.match(globalStyles, /#main-content table tbody tr \{/);
  assert.match(globalStyles, /#main-content table tbody tr:hover,/);
  assert.match(globalStyles, /#main-content table tbody tr:focus-within \{/);
  assert.match(globalStyles, /transform: translateY\(-2px\) scale\(1\.005\);/);
  assert.match(globalStyles, /box-shadow: 0 12px 24px rgba\(68, 64, 60, 0\.14\);/);
  assert.match(globalStyles, /prefers-reduced-motion: reduce/);

  console.log('admin-page-shell-copy.test.ts passed');
}
