import { runAdminAccountCoreTests } from './admin-account-core.test';
import { runAdminActionBoundaryGuardTests } from './admin-action-boundary-guard.test';
import { runAdminAuthCoreTests } from './admin-auth-core.test';
import { runAdminRoleBoundaryTests } from './admin-role-boundary.test';
import { runCheckoutCapacityHoldTests } from './checkout-capacity-hold.test';
import { runCheckoutStateMachineTests } from './checkout-state-machine.test';
import { runCmsCategoryServiceTests } from './cms-category-service.test';
import { runCmsHomepageServiceTests } from './cms-homepage-service.test';
import { runCmsInquiryServiceTests } from './cms-inquiry-service.test';
import { runCmsMediaServiceTests } from './cms-media-service.test';
import { runCmsProductServiceTests } from './cms-product-service.test';
import { runCmsServiceTypesTests } from './cms-service-types.test';
import { runCustomerAuthIdentityTests } from './customer-auth-identity.test';
import { runDataSafetyReadinessTests } from './data-safety-readiness.test';
import { runDeployReadinessTests } from './deploy-readiness.test';
import { runI18nLocalizationTests } from './i18n-localization.test';
import { runInquiryAssignmentQueueTests } from './inquiry-assignment-queue.test';
import { runInquiryAssignmentTests } from './inquiry-assignment.test';
import { runInquiryNotificationsCoreTests } from './inquiry-notifications-core.test';
import { runInquiryReportingTests } from './inquiry-reporting.test';
import { runInquiryWorkflowTests } from './inquiry-workflow.test';
import { runMediaStorageReadinessTests } from './media-storage-readiness.test';
import { runOtpRateLimitTests } from './otp-rate-limit.test';
import { runPaymentGatewayAdaptersTests } from './payment-gateway-adapters.test';
import { runPaymentGatewayConfigTests } from './payment-gateway-config.test';
import { runProductCheckoutPolicyTests } from './product-checkout-policy.test';
import { runPublicInquiryServiceTests } from './public-inquiry-service.test';
import { runRepositoryFallbackPolicyTests } from './repository-fallback-policy.test';
import { runRuntimeModeTests } from './runtime-mode.test';
import { runRuntimeReadinessTests } from './runtime-readiness.test';

async function main() {
  await runRuntimeModeTests();
  await runRepositoryFallbackPolicyTests();
  await runRuntimeReadinessTests();
  await runMediaStorageReadinessTests();
  await runDataSafetyReadinessTests();
  await runDeployReadinessTests();
  await runAdminActionBoundaryGuardTests();
  await runAdminAuthCoreTests();
  await runAdminAccountCoreTests();
  await runAdminRoleBoundaryTests();
  await runCmsServiceTypesTests();
  await runCmsMediaServiceTests();
  await runCmsCategoryServiceTests();
  await runCmsProductServiceTests();
  await runCmsHomepageServiceTests();
  await runCmsInquiryServiceTests();
  await runPublicInquiryServiceTests();
  await runInquiryNotificationsCoreTests();
  await runInquiryWorkflowTests();
  await runInquiryReportingTests();
  await runInquiryAssignmentTests();
  await runInquiryAssignmentQueueTests();
  await runCustomerAuthIdentityTests();
  await runOtpRateLimitTests();
  await runCheckoutStateMachineTests();
  await runCheckoutCapacityHoldTests();
  await runPaymentGatewayConfigTests();
  await runPaymentGatewayAdaptersTests();
  await runProductCheckoutPolicyTests();
  await runI18nLocalizationTests();
  console.log('unit tests passed (30 files)');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
