import { runAdminAccountCoreTests } from './admin-account-core.test';
import { runAdminActionBoundaryGuardTests } from './admin-action-boundary-guard.test';
import { runAdminAuthCoreTests } from './admin-auth-core.test';
import { runAdminOrderCustomerAssignmentFlowTests } from './admin-order-customer-assignment-flow.test';
import { runAdminOrderLineEditFlowTests } from './admin-order-line-edit-flow.test';
import { runAdminRoleBoundaryTests } from './admin-role-boundary.test';
import { runCheckoutActionNextPathTests } from './checkout-action-next-path.test';
import { runCheckoutAdapterAliasAttemptTests } from './checkout-adapter-alias-attempt.test';
import { runCheckoutCapacityHoldTests } from './checkout-capacity-hold.test';
import { runCheckoutPaymentProviderTests } from './checkout-payment-provider.test';
import { runCheckoutStateMachineTests } from './checkout-state-machine.test';
import { runCmsCategoryServiceTests } from './cms-category-service.test';
import { runCmsHomepageServiceTests } from './cms-homepage-service.test';
import { runCmsInquiryServiceTests } from './cms-inquiry-service.test';
import { runCmsMediaServiceTests } from './cms-media-service.test';
import { runCmsProductServiceTests } from './cms-product-service.test';
import { runCmsServiceTypesTests } from './cms-service-types.test';
import { runCustomerAdminTimelineModelTests } from './customer-admin-timeline-model.test';
import { runCustomerAuthIdentityTests } from './customer-auth-identity.test';
import { runCustomerPrivacyTests } from './customer-privacy.test';
import { runDataSafetyReadinessTests } from './data-safety-readiness.test';
import { runDeployReadinessTests } from './deploy-readiness.test';
import { runFulfillmentMethodSettingsModelTests } from './fulfillment-method-settings-model.test';
import { runFulfillmentShipmentRecordsModelTests } from './fulfillment-shipment-records-model.test';
import { runI18nLocalizationTests } from './i18n-localization.test';
import { runInquiryAssignmentQueueTests } from './inquiry-assignment-queue.test';
import { runInquiryAssignmentTests } from './inquiry-assignment.test';
import { runInquiryNotificationsCoreTests } from './inquiry-notifications-core.test';
import { runInquiryReportingTests } from './inquiry-reporting.test';
import { runInquiryWorkflowTests } from './inquiry-workflow.test';
import { runInventoryStockReservationModelTests } from './inventory-stock-reservation-model.test';
import { runManualPaymentAdjustmentFlowTests } from './manual-payment-adjustment-flow.test';
import { runManualPaymentMarkingFlowTests } from './manual-payment-marking-flow.test';
import { runMediaStorageReadinessTests } from './media-storage-readiness.test';
import { runOrderActivityTimelineAttributionTests } from './order-activity-timeline-attribution.test';
import { runOrderNextPathTests } from './order-next-path.test';
import { runOrderDiscountFlowTests } from './order-discount-flow.test';
import { runOrderNotificationActionsFlowTests } from './order-notification-actions-flow.test';
import { runOrderReturnRouteCoreTests } from './order-return-route-core.test';
import { runOtpRateLimitTests } from './otp-rate-limit.test';
import { runPaymentGatewayAdaptersTests } from './payment-gateway-adapters.test';
import { runPaymentGatewayConfigTests } from './payment-gateway-config.test';
import { runPaymentAttemptTimelineFlowTests } from './payment-attempt-timeline-flow.test';
import { runPaymentProviderAliasCoreTests } from './payment-provider-alias-core.test';
import { runPaymentProviderModeTests } from './payment-provider-mode.test';
import { runPaymentProviderRuntimeCoreTests } from './payment-provider-runtime-core.test';
import { runPaymentResultCoreTests } from './payment-result-core.test';
import { runProductCheckoutPolicyTests } from './product-checkout-policy.test';
import { runProductVariantMapperTests } from './product-variant-mapper.test';
import { runPromotionDiscountModelTests } from './promotion-discount-model.test';
import { runPromotionEligibilityRulesModelTests } from './promotion-eligibility-rules-model.test';
import { runPromotionUsageLimitsModelTests } from './promotion-usage-limits-model.test';
import { runPromotionValidityWindowsModelTests } from './promotion-validity-windows-model.test';
import { runPromotionVoucherModelTests } from './promotion-voucher-model.test';
import { runPublicInquiryServiceTests } from './public-inquiry-service.test';
import { runRepositoryFallbackPolicyTests } from './repository-fallback-policy.test';
import { runRuntimeModeTests } from './runtime-mode.test';
import { runRuntimeReadinessTests } from './runtime-readiness.test';
import { runStaffOrderDraftFlowTests } from './staff-order-draft-flow.test';
import { runVariantCheckoutLineModelTests } from './variant-checkout-line-model.test';
import { runVariantLocationStockModelTests } from './variant-location-stock-model.test';
import { runVariantStockMigrationTests } from './variant-stock-migration.test';
import { runVariantStockAuditTests } from './variant-stock-audit.test';
import { runVariantStockStatusTests } from './variant-stock-status.test';
import { runWarehouseLocationModelTests } from './warehouse-location-model.test';

async function main() {
  await runRuntimeModeTests();
  await runRepositoryFallbackPolicyTests();
  await runRuntimeReadinessTests();
  await runMediaStorageReadinessTests();
  await runDataSafetyReadinessTests();
  await runDeployReadinessTests();
  await runAdminActionBoundaryGuardTests();
  await runAdminAuthCoreTests();
  await runAdminAccountCoreTests();
  await runAdminRoleBoundaryTests();
  await runCmsServiceTypesTests();
  await runCmsMediaServiceTests();
  await runCmsCategoryServiceTests();
  await runCmsProductServiceTests();
  await runCmsHomepageServiceTests();
  await runCmsInquiryServiceTests();
  await runPublicInquiryServiceTests();
  await runInquiryNotificationsCoreTests();
  await runInquiryWorkflowTests();
  await runInquiryReportingTests();
  await runInquiryAssignmentTests();
  await runInquiryAssignmentQueueTests();
  await runCustomerAdminTimelineModelTests();
  await runCustomerAuthIdentityTests();
  await runCustomerPrivacyTests();
  await runOtpRateLimitTests();
  await runCheckoutStateMachineTests();
  await runCheckoutCapacityHoldTests();
  await runCheckoutPaymentProviderTests();
  await runCheckoutAdapterAliasAttemptTests();
  await runPaymentProviderAliasCoreTests();
  await runPaymentProviderModeTests();
  await runPaymentProviderRuntimeCoreTests();
  await runPaymentResultCoreTests();
  await runOrderNextPathTests();
  await runOrderReturnRouteCoreTests();
  await runCheckoutActionNextPathTests();
  await runStaffOrderDraftFlowTests();
  await runAdminOrderLineEditFlowTests();
  await runAdminOrderCustomerAssignmentFlowTests();
  await runManualPaymentMarkingFlowTests();
  await runManualPaymentAdjustmentFlowTests();
  await runPaymentAttemptTimelineFlowTests();
  await runOrderDiscountFlowTests();
  await runOrderActivityTimelineAttributionTests();
  await runOrderNotificationActionsFlowTests();
  await runPaymentGatewayConfigTests();
  await runPaymentGatewayAdaptersTests();
  await runProductCheckoutPolicyTests();
  await runProductVariantMapperTests();
  await runPromotionDiscountModelTests();
  await runPromotionVoucherModelTests();
  await runPromotionValidityWindowsModelTests();
  await runPromotionUsageLimitsModelTests();
  await runPromotionEligibilityRulesModelTests();
  await runVariantCheckoutLineModelTests();
  await runVariantStockAuditTests();
  await runVariantStockStatusTests();
  await runVariantStockMigrationTests();
  await runVariantLocationStockModelTests();
  await runWarehouseLocationModelTests();
  await runFulfillmentMethodSettingsModelTests();
  await runFulfillmentShipmentRecordsModelTests();
  await runInventoryStockReservationModelTests();
  await runI18nLocalizationTests();
  console.log('unit tests passed (65 files)');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
