import { runAdminAccountCoreTests } from './admin-account-core.test';
import { runAdminActionBoundaryGuardTests } from './admin-action-boundary-guard.test';
import { runAdminAuthCoreTests } from './admin-auth-core.test';
import { runAdminModuleAccessTests } from './admin-module-access.test';
import { runAdminOrderCustomerAssignmentFlowTests } from './admin-order-customer-assignment-flow.test';
import { runAdminOrderLineEditFlowTests } from './admin-order-line-edit-flow.test';
import { runAdminRoleBoundaryTests } from './admin-role-boundary.test';
import { runApiTokenManagementTests } from './api-token-management.test';
import { runBestSellingProductsTests } from './best-selling-products.test';
import { runChannelPriceOverrideModelTests } from './channel-price-override-model.test';
import { runChannelProductAvailabilityModelTests } from './channel-product-availability-model.test';
import { runChannelStorefrontModelTests } from './channel-storefront-model.test';
import { runCheckoutActionNextPathTests } from './checkout-action-next-path.test';
import { runCheckoutAdapterAliasAttemptTests } from './checkout-adapter-alias-attempt.test';
import { runCheckoutCapacityHoldTests } from './checkout-capacity-hold.test';
import { runCheckoutPaymentProviderTests } from './checkout-payment-provider.test';
import { runCheckoutStateMachineTests } from './checkout-state-machine.test';
import { runCmsCategoryServiceTests } from './cms-category-service.test';
import { runCmsHomepageServiceTests } from './cms-homepage-service.test';
import { runCmsInquiryServiceTests } from './cms-inquiry-service.test';
import { runCmsMediaServiceTests } from './cms-media-service.test';
import { runCmsProductServiceTests } from './cms-product-service.test';
import { runCmsServiceTypesTests } from './cms-service-types.test';
import { runCustomerAdminTimelineModelTests } from './customer-admin-timeline-model.test';
import { runCustomerAuthIdentityTests } from './customer-auth-identity.test';
import { runCustomerPrivacyTests } from './customer-privacy.test';
import { runDashboardExtensionMountPointsTests } from './dashboard-extension-mount-points.test';
import { runDataSafetyReadinessTests } from './data-safety-readiness.test';
import { runDeployReadinessTests } from './deploy-readiness.test';
import { runFailedPaymentNotificationAlertsTests } from './failed-payment-notification-alerts.test';
import { runFulfillmentMethodSettingsModelTests } from './fulfillment-method-settings-model.test';
import { runFulfillmentQueueSummaryTests } from './fulfillment-queue-summary.test';
import { runFulfillmentShipmentRecordsModelTests } from './fulfillment-shipment-records-model.test';
import { runHomepageBannerMediaSettingsTests } from './homepage-banner-media-settings.test';
import { runI18nLocalizationTests } from './i18n-localization.test';
import { runImportExportJobTrackingTests } from './import-export-job-tracking.test';
import { runInquiryAssignmentQueueTests } from './inquiry-assignment-queue.test';
import { runInquiryAssignmentTests } from './inquiry-assignment.test';
import { runInquiryNotificationsCoreTests } from './inquiry-notifications-core.test';
import { runInquiryOperationsSummaryTests } from './inquiry-operations-summary.test';
import { runInquiryReportingTests } from './inquiry-reporting.test';
import { runInquiryWorkflowTests } from './inquiry-workflow.test';
import { runIntegrationAppRegistryTests } from './integration-app-registry.test';
import { runInventoryStockReservationModelTests } from './inventory-stock-reservation-model.test';
import { runLaunchReadinessHealthTests } from './launch-readiness-health.test';
import { runLocaleAwareMediaAltTextTests } from './locale-aware-media-alt-text.test';
import { runLocalizedSeoMetadataModelTests } from './localized-seo-metadata-model.test';
import { runLowStockAlertsTests } from './low-stock-alerts.test';
import { runManualPaymentAdjustmentFlowTests } from './manual-payment-adjustment-flow.test';
import { runManualPaymentMarkingFlowTests } from './manual-payment-marking-flow.test';
import { runMediaStorageReadinessTests } from './media-storage-readiness.test';
import { runNotificationProviderSettingsTests } from './notification-provider-settings.test';
import { runOrderActivityTimelineAttributionTests } from './order-activity-timeline-attribution.test';
import { runOrderNextPathTests } from './order-next-path.test';
import { runOrderDiscountFlowTests } from './order-discount-flow.test';
import { runOrderNotificationActionsFlowTests } from './order-notification-actions-flow.test';
import { runOrderReturnRouteCoreTests } from './order-return-route-core.test';
import { runOrderRevenueSummaryTests } from './order-revenue-summary.test';
import { runOtpRateLimitTests } from './otp-rate-limit.test';
import { runPaymentAttemptTimelineFlowTests } from './payment-attempt-timeline-flow.test';
import { runPaymentGatewayAdaptersTests } from './payment-gateway-adapters.test';
import { runPaymentGatewayConfigTests } from './payment-gateway-config.test';
import { runPaymentGatewayLaunchDocsTests } from './payment-gateway-launch-docs.test';
import { runPaymentProviderAliasCoreTests } from './payment-provider-alias-core.test';
import { runPaymentProviderModeTests } from './payment-provider-mode.test';
import { runPaymentProviderRuntimeCoreTests } from './payment-provider-runtime-core.test';
import { runPaymentProviderSettingsTests } from './payment-provider-settings.test';
import { runPaymentResultCoreTests } from './payment-result-core.test';
import { runPaymentSettlementAdminPanelTests } from './payment-settlement-admin-panel.test';
import { runPaymentSettlementNavigationTests } from './payment-settlement-navigation.test';
import { runPaymentSettlementReconciliationTests } from './payment-settlement-reconciliation.test';
import { runPaymentSettlementRepositoryTests } from './payment-settlement-repository.test';
import { runPaymentSettlementServiceTests } from './payment-settlement-service.test';
import { runPaymentWebhookAlertNavigationTests } from './payment-webhook-alert-navigation.test';
import { runPaymentWebhookAlertServicePanelTests } from './payment-webhook-alert-service-panel.test';
import { runPaymentWebhookAlertsTests } from './payment-webhook-alerts.test';
import { runPaymentWebhookRouteCoreTests } from './payment-webhook-route-core.test';
import { runPaymentWebhookServiceTests } from './payment-webhook-service.test';
import { runPaymentWebhookServiceSettlementTests } from './payment-webhook-service-settlement.test';
import { runPaymentWebhookServiceTransitionTests } from './payment-webhook-service-transition.test';
import { runPaymentWebhookSignatureTests } from './payment-webhook-signature.test';
import { runPaymentWebhookTransitionPlanTests } from './payment-webhook-transition-plan.test';
import { runProductCheckoutPolicyTests } from './product-checkout-policy.test';
import { runProductVariantMapperTests } from './product-variant-mapper.test';
import { runPromotionAuditLogsModelTests } from './promotion-audit-logs-model.test';
import { runPromotionDiscountModelTests } from './promotion-discount-model.test';
import { runPromotionEligibilityRulesModelTests } from './promotion-eligibility-rules-model.test';
import { runPromotionOrderMinimumsModelTests } from './promotion-order-minimums-model.test';
import { runPromotionSchemaParityTests } from './promotion-schema-parity.test';
import { runPromotionStoreCreditFoundationModelTests } from './promotion-store-credit-foundation-model.test';
import { runPromotionUsageLimitsModelTests } from './promotion-usage-limits-model.test';
import { runPromotionValidityWindowsModelTests } from './promotion-validity-windows-model.test';
import { runPromotionVoucherModelTests } from './promotion-voucher-model.test';
import { runProviderDiagnosticsTests } from './provider-diagnostics.test';
import { runPublicInquiryServiceTests } from './public-inquiry-service.test';
import { runRecentActivitySummaryTests } from './recent-activity-summary.test';
import { runRepositoryFallbackPolicyTests } from './repository-fallback-policy.test';
import { runRuntimeModeTests } from './runtime-mode.test';
import { runRuntimeReadinessTests } from './runtime-readiness.test';
import { runShippingDeliverySettingsTests } from './shipping-delivery-settings.test';
import { runStaffOrderDraftFlowTests } from './staff-order-draft-flow.test';
import { runStaffPermissionSettingsTests } from './staff-permission-settings.test';
import { runStorefrontNavigationMenuBuilderTests } from './storefront-navigation-menu-builder.test';
import { runStoreSettingsPageTests } from './store-settings-page.test';
import { runTaxCategorySettingsTests } from './tax-category-settings.test';
import { runTranslationCompletenessDashboardTests } from './translation-completeness-dashboard.test';
import { runVariantCheckoutLineModelTests } from './variant-checkout-line-model.test';
import { runVariantLocationStockModelTests } from './variant-location-stock-model.test';
import { runVariantStockMigrationTests } from './variant-stock-migration.test';
import { runVariantStockAuditTests } from './variant-stock-audit.test';
import { runVariantStockStatusTests } from './variant-stock-status.test';
import { runWarehouseLocationModelTests } from './warehouse-location-model.test';
import { runWebhookConfigurationTests } from './webhook-configuration.test';
import { runWebhookEventLogTests } from './webhook-event-log.test';

async function main() {
  await runRuntimeModeTests();
  await runRepositoryFallbackPolicyTests();
  await runRuntimeReadinessTests();
  await runMediaStorageReadinessTests();
  await runDataSafetyReadinessTests();
  await runDeployReadinessTests();
  await runAdminActionBoundaryGuardTests();
  await runAdminAuthCoreTests();
  await runAdminAccountCoreTests();
  await runAdminRoleBoundaryTests();
  await runAdminModuleAccessTests();
  await runCmsServiceTypesTests();
  await runCmsMediaServiceTests();
  await runCmsCategoryServiceTests();
  await runCmsProductServiceTests();
  await runCmsHomepageServiceTests();
  await runCmsInquiryServiceTests();
  await runPublicInquiryServiceTests();
  await runInquiryNotificationsCoreTests();
  await runInquiryWorkflowTests();
  await runInquiryReportingTests();
  await runInquiryAssignmentTests();
  await runInquiryAssignmentQueueTests();
  await runInquiryOperationsSummaryTests();
  await runCustomerAdminTimelineModelTests();
  await runCustomerAuthIdentityTests();
  await runCustomerPrivacyTests();
  await runOtpRateLimitTests();
  await runCheckoutStateMachineTests();
  await runCheckoutCapacityHoldTests();
  await runCheckoutPaymentProviderTests();
  await runCheckoutAdapterAliasAttemptTests();
  await runPaymentProviderAliasCoreTests();
  await runPaymentProviderModeTests();
  await runPaymentProviderRuntimeCoreTests();
  await runPaymentResultCoreTests();
  await runOrderNextPathTests();
  await runOrderReturnRouteCoreTests();
  await runCheckoutActionNextPathTests();
  await runStaffOrderDraftFlowTests();
  await runAdminOrderLineEditFlowTests();
  await runAdminOrderCustomerAssignmentFlowTests();
  await runManualPaymentMarkingFlowTests();
  await runManualPaymentAdjustmentFlowTests();
  await runPaymentAttemptTimelineFlowTests();
  await runOrderDiscountFlowTests();
  await runOrderActivityTimelineAttributionTests();
  await runOrderNotificationActionsFlowTests();
  await runOrderRevenueSummaryTests();
  await runBestSellingProductsTests();
  await runLowStockAlertsTests();
  await runFulfillmentQueueSummaryTests();
  await runRecentActivitySummaryTests();
  await runFailedPaymentNotificationAlertsTests();
  await runLaunchReadinessHealthTests();
  await runPaymentGatewayConfigTests();
  await runPaymentGatewayAdaptersTests();
  await runPaymentGatewayLaunchDocsTests();
  await runPaymentProviderSettingsTests();
  await runPaymentWebhookServiceTests();
  await runPaymentWebhookRouteCoreTests();
  await runPaymentWebhookSignatureTests();
  await runPaymentWebhookTransitionPlanTests();
  await runPaymentWebhookServiceTransitionTests();
  await runPaymentSettlementReconciliationTests();
  await runPaymentSettlementServiceTests();
  await runPaymentSettlementRepositoryTests();
  await runPaymentWebhookServiceSettlementTests();
  await runPaymentSettlementAdminPanelTests();
  await runPaymentSettlementNavigationTests();
  await runPaymentWebhookAlertsTests();
  await runPaymentWebhookAlertServicePanelTests();
  await runPaymentWebhookAlertNavigationTests();
  await runNotificationProviderSettingsTests();
  await runWebhookConfigurationTests();
  await runWebhookEventLogTests();
  await runIntegrationAppRegistryTests();
  await runApiTokenManagementTests();
  await runProviderDiagnosticsTests();
  await runDashboardExtensionMountPointsTests();
  await runImportExportJobTrackingTests();
  await runStaffPermissionSettingsTests();
  await runProductCheckoutPolicyTests();
  await runProductVariantMapperTests();
  await runPromotionDiscountModelTests();
  await runPromotionVoucherModelTests();
  await runPromotionValidityWindowsModelTests();
  await runPromotionUsageLimitsModelTests();
  await runPromotionEligibilityRulesModelTests();
  await runPromotionOrderMinimumsModelTests();
  await runPromotionStoreCreditFoundationModelTests();
  await runPromotionAuditLogsModelTests();
  await runPromotionSchemaParityTests();
  await runChannelStorefrontModelTests();
  await runChannelProductAvailabilityModelTests();
  await runChannelPriceOverrideModelTests();
  await runLocalizedSeoMetadataModelTests();
  await runTranslationCompletenessDashboardTests();
  await runLocaleAwareMediaAltTextTests();
  await runStoreSettingsPageTests();
  await runStorefrontNavigationMenuBuilderTests();
  await runHomepageBannerMediaSettingsTests();
  await runShippingDeliverySettingsTests();
  await runTaxCategorySettingsTests();
  await runVariantCheckoutLineModelTests();
  await runVariantStockAuditTests();
  await runVariantStockStatusTests();
  await runVariantStockMigrationTests();
  await runVariantLocationStockModelTests();
  await runWarehouseLocationModelTests();
  await runFulfillmentMethodSettingsTests();
  await runFulfillmentShipmentRecordsModelTests();
  await runInventoryStockReservationModelTests();
  await runI18nLocalizationTests();
  console.log('unit tests passed (114 files)');
}

main().catch((error) => {
  console.error(error);
  throw error;
});