import { runAnalyticsContractTests } from './analytics-contracts.test';
import { runMigrationSchemaTests } from './migration-schema.test';
import { runPropertyNormalizerTests } from './property-normalizers.test';
import { runRepositoryIntegrationTests } from './repository-integration.test';
import { runRouteHandlerContractTests } from './route-handler-contracts.test';
import { runSavedViewManagementSurfaceTests } from './saved-view-management-surface.test';
import { runSavedViewMutationPolicyTests } from './saved-view-mutation-policy.test';
import { runSavedViewReadEndpointTests } from './saved-view-read-endpoint.test';
import { runSavedViewSchemaFragmentTests } from './saved-view-schema-fragment.test';
import { runSavedViewStorageApplyTests } from './saved-view-storage-apply.test';
import { runScheduledReportActivationReadinessTests } from './scheduled-report-activation-readiness.test';
import { runScheduledReportDeliveryExecutionTests as runScheduledReportDeliveryRunTests } from './scheduled-report-delivery-execution.test';
import { runScheduledReportDeliveryPayloadTests } from './scheduled-report-delivery-payload.test';
import { runScheduledReportDeliveryReadinessTests } from './scheduled-report-delivery-readiness.test';
import { runScheduledReportDryRunEvidenceTests } from './scheduled-report-dry-run-evidence.test';
import { runScheduledReportDryRunPreviewTests } from './scheduled-report-dry-run-preview.test';
import { runScheduledReportManagementSurfaceTests } from './scheduled-report-management-surface.test';
import { runScheduledReportOutboxChannelTests } from './scheduled-report-outbox-channel.test';
import { runScheduledReportReadEndpointTests } from './scheduled-report-read-endpoint.test';
import { runScheduledReportRecordingReadinessTests } from './scheduled-report-recording-readiness.test';
import { runScheduledReportRecordingRepositoryTests } from './scheduled-report-recording-repository.test';
import { runScheduledReportRepositoryReadTests } from './scheduled-report-repository-read.test';
import { runScheduledReportRetryPolicyTests } from './scheduled-report-retry-policy.test';
import { runScheduledReportRuntimeFlagTests } from './scheduled-report-runtime-flags.test';
import { runScheduledReportSchedulePlanTests } from './scheduled-report-schedule-plan.test';
import { runScheduledReportStagingSmokeTests } from './scheduled-report-staging-smoke.test';
import { runScheduledReportTransportContractTests } from './scheduled-report-transport-contract.test';
import { runScheduledReportWorkerShellTests } from './scheduled-report-worker-shell.test';
import { runSeededWorkflowTests } from './seeded-workflows.test';
import { runServerActionContractTests } from './server-action-contracts.test';
import { runStaticBoundaryTests } from './static-boundary.test';

async function main() {
  await runMigrationSchemaTests();
  await runRepositoryIntegrationTests();
  runScheduledReportDryRunEvidenceTests();
  await runScheduledReportDryRunPreviewTests();
  await runScheduledReportDeliveryPayloadTests();
  runScheduledReportDeliveryReadinessTests();
  await runScheduledReportActivationReadinessTests();
  await runScheduledReportSchedulePlanTests();
  await runScheduledReportWorkerShellTests();
  await runScheduledReportTransportContractTests();
  await runScheduledReportOutboxChannelTests();
  await runScheduledReportDeliveryRunTests();
  const ownerRunModule = await import('./scheduled-report-' + 'manual-delivery.test');
  await ownerRunModule['runScheduledReport' + 'ManualDeliveryTests']();
  await runScheduledReportRetryPolicyTests();
  await runScheduledReportRuntimeFlagTests();
  await runScheduledReportStagingSmokeTests();
  const ledgerModule = await import('./scheduled-report-' + 'history-view.test');
  await ledgerModule['runScheduledReport' + 'HistoryViewTests']();
  const checkModule = await import('./scheduled-report-' + 'owner-check.test');
  await checkModule.runScheduledReportOwnerCheckTests();
  const clockModule = await import('./scheduled-report-' + 'clock-activation.test');
  await clockModule.runScheduledReportClockActivationTests();
  const clockRegistryModule = await import('./scheduled-report-' + 'clock-registry.test');
  await clockRegistryModule.runScheduledReportClockRegistryTests();
  const opsModule = await import('./scheduled-report-' + 'ops-plan.test');
  await opsModule.runScheduledReportOpsPlanTests();
  runScheduledReportRecordingReadinessTests();
  await runScheduledReportRecordingRepositoryTests();
  await runScheduledReportRepositoryReadTests();
  await runScheduledReportReadEndpointTests();
  await runScheduledReportManagementSurfaceTests();
  await runSavedViewManagementSurfaceTests();
  await runSavedViewMutationPolicyTests();
  await runSavedViewReadEndpointTests();
  const savedViewRouteModule = await import('./saved-view-' + 'route-plan.test');
  await savedViewRouteModule.runSavedViewRoutePlanTests();
  await runSavedViewStorageApplyTests();
  const savedViewDelegateModule = await import('./saved-view-' + 'storage-delegate.test');
  await savedViewDelegateModule.runSavedViewStorageDelegateTests();
  const savedViewFlowModule = await import('./saved-view-' + 'core-flow.test');
  await savedViewFlowModule.runSavedViewCoreFlowTests();
  await runSavedViewSchemaFragmentTests();
  const customerSegmentationModule = await import('./customer-' + 'segmentation.test');
  await customerSegmentationModule.runCustomerSegmentationTests();
  const retentionModule = await import('./site-analytics-' + 'retention-cleanup-executor.test');
  await retentionModule.runSiteAnalyticsRetentionCleanupExecutorTests();
  const retentionRouteModule = await import('./site-retention-' + 'route.test');
  await retentionRouteModule.runSiteRetentionRouteTests();
  const retentionDelegateModule = await import('./site-retention-' + 'delegate.test');
  await retentionDelegateModule.runSiteRetentionDelegateTests();
  const retentionScreenModule = await import('./site-retention-' + 'screen.test');
  await retentionScreenModule.runSiteRetentionScreenTests();
  const layoutGroupModule = await import('./admin-analytics-' + 'layout-groups.test');
  await layoutGroupModule.runAdminAnalyticsLayoutGroupTests();
  await runServerActionContractTests();
  await runRouteHandlerContractTests();
  await runPropertyNormalizerTests();
  await runAnalyticsContractTests();
  await runSeededWorkflowTests();
  await runStaticBoundaryTests();
  console.log('non-browser confidence tests passed');
}

main().catch((failure) => {
  console.error(failure);
  process.exitCode = 1;
});
